export const CHATS_FETCHED = 'chats.CHATS_FETCHED';
export const USER_MESSAGES_FETCHED = 'chats.USER_MESSAGES_FETCHED';
export const SERVICE_FETCHED = 'chats.SERVICE_FETCHED';
export const SERVICE_OWNER_FETCHED = 'chats.SERVICE_OWNER_FETCHED';
export const APPEND_MESSAGE = 'chats.APPEND_MESSAGE';
