export const SERVICE_SEARCH_FETCHED = 'search.SEARCH_FETCHED';
export const SERVICE_SEARCH_RESET = 'search.SEARCH_RESET';

export const PROFILE_SEARCH_FETCHED = 'search.PROFILE_SEARCH_FETCHED';
export const PROFILE_SEARCH_RESET = 'search.PROFILE_SEARCH_RESET';
