export const KEYCLOAK_INITIALIZED = 'auth.KEYCLOAK_INITIALIZED';
export const KEYCLOAK_PROFILE_FETCHED = 'auth.KEYCLOAK_PROFILE_FETCHED';
export const USER_PROFILE_FETCHED = 'auth.USER_PROFILE_FETCHED';
